Repository konveyor/forklift-ui, pull requests merged in 2021-02, with the labels that each got.

#405 [BZ#1900343] Patch provider secrets with owner references
  src/app/client/helpers.ts
  src/app/queries/providers.ts
Labels: v2.0.0-beta.0/yes

#410 Adding end-to-end happy path for migration plan
  qe-tests/cypress/integration/models/plan.ts
  qe-tests/cypress/integration/models/provider.ts
  qe-tests/cypress/integration/models/providerVmware.ts
  qe-tests/cypress/integration/tests/basicFlowTest.ts
  qe-tests/cypress/integration/tests/config.ts
  qe-tests/cypress/integration/tests/createMappingsTest.ts
  qe-tests/cypress/integration/tests/createPlanTest.ts
  qe-tests/cypress/integration/tests/endToEndTest.ts
  qe-tests/cypress/integration/types/constants.ts
  qe-tests/cypress/integration/types/types.ts
  qe-tests/cypress/integration/views/plan.view.ts
  qe-tests/cypress/integration/views/providerVmware.view.ts
  qe-tests/cypress/utils/utils.ts
  qe-tests/tsconfig.json
Labels: qe-tests

#412 Use selfLink instead of name to uniquely identify VMs in selection state
  src/app/Plans/components/Wizard/SelectVMsForm.tsx
Labels: v2.0.0-beta.0/yes

#414 Correctly use namespace from meta.json instead of hard-coded 'openshift-migration' when adding providers
  src/app/client/helpers.ts
Labels: high-priority, v2.0.0-beta.0/yes

#415 [Backport] Correctly use namespace from meta.json instead of hard-coded 'openshift-migration' when adding providers (#414)
  src/app/client/helpers.ts
Labels: high-priority

#416 Adding ocp provider
  qe-tests/cypress/integration/models/mapping.ts
  qe-tests/cypress/integration/models/mappingNetwork.ts
  qe-tests/cypress/integration/models/mappingStorage.ts
  qe-tests/cypress/integration/models/plan.ts
  qe-tests/cypress/integration/models/provider.ts
  qe-tests/cypress/integration/models/providerOcpVirt.ts
  qe-tests/cypress/integration/models/providerVmware.ts
  qe-tests/cypress/integration/tests/basicFlowTest.ts
  qe-tests/cypress/integration/tests/createMappingsTest.ts
  qe-tests/cypress/integration/tests/createPlanTest.ts
  qe-tests/cypress/integration/tests/endToEndTest.ts
  qe-tests/cypress/integration/tests/ocpvirt/ocpCrud.ts
  qe-tests/cypress/integration/tests/ocpvirt/ocpVirtConfig.ts
  qe-tests/cypress/integration/tests/ocpvirt/ovirtCreateTest.ts
  qe-tests/cypress/integration/tests/vmware/basicFlowTest.ts
  qe-tests/cypress/integration/tests/vmware/config.ts
  qe-tests/cypress/integration/tests/vmware/createMappingsTest.ts
  qe-tests/cypress/integration/tests/vmware/createPlanTest.ts
  qe-tests/cypress/integration/tests/vmware/endToEndTest.ts
  qe-tests/cypress/integration/types/constants.ts
  qe-tests/cypress/integration/types/types.ts
  qe-tests/cypress/integration/views/menu.view.ts
  qe-tests/cypress/integration/views/plan.view.ts
  qe-tests/cypress/utils/utils.ts
  qe-tests/package-lock.json
Labels: qe-tests
